[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["stripe"]

[functions."charge-balances"]
  schedule = "0 14 * * *"

[functions."send-reminders"]
  schedule = "0 14 * * *"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "POST, GET, OPTIONS"
